name: movie_bloc
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  test: flutter test
  analyze: flutter analyze --no-pub
  format: flutter format lib/**

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.0.1

  # Network
  dio: ^4.0.6

  # Utilities
  logging: ^1.0.2
  get_it: ^7.2.0
  connectivity_plus: ^2.3.0

  # DB
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.2.0

  # Ui
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^8.2.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  logger: ^1.1.0
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/